.TH QCCPACKVID 3 "QCCPACKVID" ""
.SH NAME
QccPackVID \- QccPack module for video
.SH DESCRIPTION
.B QccPackVID
provides a collection of library routines and utility programs for
video coding of image sequences.
.SS "DATA TYPES AND FILE FORMATS"
.TP
.BR QccVIDMotionVectorsTable (3)
data structure 
.B QccVIDMotionVectorsTable
for the Huffman coding of motion vectors as specified in the H.261
standard
.SS "LIBRARY ROUTINES"
.SS "Motion-Vector Coding"
.TP
.BR QccVIDMotionVectorsTableInitialize (3)
initialize H.261 motion-vector coding table
.TP
.BR QccVIDMotionVectorsTableCreate (3)
create H.261 motion-vector coding table
.TP
.BR QccVIDMotionVectorsTableFree (3)
free H.261 motion-vector coding table
.TP
.BR QccVIDMotionVectorsEncode (3)
encode motion vectors using H.261 method
.TP
.BR QccVIDMotionVectorsDecode (3)
decode motion vectors using H.261 method
.TP
.BR QccVIDMotionVectorsReadFile (3)
read file of motion vectors
.TP
.BR QccVIDMotionVectorsWriteFile (3)
write file of motion vectors
.SS "Block-Based Motion Estimation and Compensation"
.TP
.BR QccVIDMotionEstimationMAE (3)
mean absolute error between blocks
.TP
.BR QccVIDMotionEstimationExtractBlock (3)
extract block from reference frame for motion estimation and motion
compensation
.TP
.BR QccVIDMotionEstimationInsertBlock (3)
insert block into current frame for motion compensation
.TP
.BR QccVIDMotionEstimationFullSearch (3)
full-search, block-based motion estimation
.TP
.BR QccVIDMotionEstimationCalcReferenceFrameSize (3)
determine size of reference frame for specified subpixel accuracy
.TP
.BR QccVIDMotionEstimationCreateReferenceFrame (3)
create reference frame by interpolating to specified subpixel accuracy
.TP
.BR QccVIDMotionEstimationCreateCompensatedFrame (3)
create motion-compensated frame according to specified motion field
.SS "Motion Estimation and Compensation Using Regular Triangle Meshes"
.TP
.BR QccVIDMeshMotionEstimationWarpMesh (3)
warp mesh from one frame to the other
.TP
.BR QccVIDMeshMotionEstimationSearch (3)
motion-estimation search for mesh vertices
.TP
.BR QccVIDMeshMotionEstimationCreateCompensatedFrame (3)
create compensated frame via transformation between two meshes
.SS "Spatial-Block Coding"
.TP
.BR QccVIDSpatialBlockEncode (3)
encode an image sequence using the spatial-block algorithm
.TP
.BR QccVIDSpatialBlockDecodeHeader (3)
decode header for spatial-block decoding
.TP
.BR QccVIDSpatialBlockDecode (3)
decode an image sequence using the spatial-block algorithm
.SS "RDWT-Block Coding"
.TP
.BR QccVIDRDWTBlockEncode (3)
encode an image sequence using the RDWT-block algorithm
.TP
.BR QccVIDRDWTBlockDecodeHeader (3)
decode header for RDWT-block decoding
.TP
.BR QccVIDRDWTBlockDecode (3)
decode an image sequence using the RDWT-block algorithm
.SS "RWMH Coding"
.TP
.BR QccVIDrwmhEncode (3)
encode an image sequence using the RWMH algorithm
.TP
.BR QccVIDrwmhDecodeHeader (3)
decode header for RWMH decoding
.TP
.BR QccVIDrwmhDecode (3)
decode an image sequence using the RWMH algorithm
.SS "UTILITY PROGRAMS"
.TP
.BR spatialblockencode (1)
encode an image sequence using the spatial-block algorithm
.TP
.BR spatialblockdecode (1)
decode an image sequence using the spatial-block algorithm
.TP
.BR rdwtblockencode (1)
encode an image sequence using the RDWT-block algorithm
.TP
.BR rdwtblockdecode (1)
decode an image sequence using the RDWT-block algorithm
.TP
.BR rwmhencode (1)
encode an image sequence using the RWMH algorithm
.TP
.BR rwmhdecode (1)
decode an image sequence using the RWMH algorithm
.TP
.BR memc (1)
full-search, block-based motion estimation and compensation
.TP
.BR mesh_memc (1)
motion estimation and compensation using regular triangle meshes
.SH "SEE ALSO"
.BR QccPackWAV (3),
.BR QccPackIMG (3),
.BR QccPackENT (3),
.BR QccPack (3)
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
