.TH QCCPACKENT 3 "QCCPACKENT" ""
.SH NAME
QccPackENT \- QccPack module for entropy coding
.SH DESCRIPTION
.B QccPackENT
provides a collection of library routines and utility programs for
entropy coding.
.SS "DATA TYPES AND FILE FORMATS"
.TP
.BR QccENTHuffmanTable (3)
data structure 
.B QccENTHuffmanTable
and corresponding
.B HUF
file format for Huffman encoding and decoding
.TP
.BR QccENTArithmeticModel (3)
data structure
.B QccENTArithmeticModel
for arithmetic encoding and decoding
.TP
.BR QccENTArithmeticGetContext (3)
data type
.B QccENTArithmeticGetContext
for functions for retrieving the current context
for symbols during arithmetic encoding and decoding
.SS "LIBRARY ROUTINES"
.SS "Huffman Coding"
.TP
.BR QccENTHuffmanTableInitialize (3)
initialize Huffman table
.TP
.BR QccENTHuffmanTableAlloc (3)
allocate Huffman table
.TP
.BR QccENTHuffmanTableFree (3)
free Huffman table
.TP
.BR QccENTHuffmanTablePrint (3)
print Huffman table
.TP
.BR QccENTHuffmanTableRead (3)
read Huffman table from file
.TP
.BR QccENTHuffmanTableWrite (3)
write Huffman table to file
.TP
.BR QccENTHuffmanTableCreateDecodeTable (3)
create Huffman table for decoding
.TP
.BR QccENTHuffmanTableCreateEncodeTable (3)
create Huffman table for encoding
.TP
.BR QccENTHuffmanEncode (3)
Huffman encode symbol stream
.TP
.BR QccENTHuffmanDecode (3)
Huffman decode symbol stream
.TP
.BR QccENTHuffmanDesign (3)
design a Huffman code table from a probability distribution
.TP
.BR QccENTHuffmanEncodeChannel (3)
Huffman encode channel
.TP
.BR QccENTHuffmanDecodeChannel (3)
Huffman decode channel
.SS "Arithmetic Coding"
.TP
.BR QccENTArithmeticFreeModel (3)
frees arithmetic model after encoding or decoding is complete
.TP
.BR QccENTArithmeticSetModelContext (3)
set context of arithmetic model
.TP
.BR QccENTArithmeticSetModelAdaption (3)
set adaption state (adaptive or nonadaptive) of arithmetic model
.TP
.BR QccENTArithmeticSetModelProbabilities (3)
explicitly set probability distribution of nonadaptive arithmetic model
.TP
.BR QccENTArithmeticEncodeStart (3)
start arithmetic encoder
.TP
.BR QccENTArithmeticEncodeEnd (3)
terminate arithmetic encoder
.TP
.BR QccENTArithmeticEncode (3)
arithmetic encode
.TP
.BR QccENTArithmeticEncodeFlush (3)
flush arithmetic encoder to output bitstream
.TP
.BR QccENTArithmeticDecodeStart (3)
start arithmetic decoder
.TP
.BR QccENTArithmeticDecodeRestart (3)
restart arithmetic decoder
.TP
.BR QccENTArithmeticDecode (3)
arithmetic decode
.SS "Golomb Coding"
.TP
.BR QccENTGolombEncode (3)
Golomb encoding for a binary sequence
.TP
.BR QccENTGolombDecode (3)
Golomb decoding for a binary sequence
.TP
.BR QccENTGolombEncodeChannel (3)
Golomb encoding for a binary channel
.TP
.BR QccENTGolombDecodeChannel (3)
Golomb decoding for a binary channel
.TP
.BR QccENTAdaptiveGolombEncode (3)
adaptive Golomb (Langdon) encoding
.TP
.BR QccENTAdaptiveGolombDecode (3)
adaptive Golomb (Langdon) decoding
.TP
.BR QccENTAdaptiveGolombEncodeChannel (3)
adaptive Golomb (Langdon) encoding for binary channels
.TP
.BR QccENTAdaptiveGolombDecodeChannel (3)
adaptive Golomb (Langdon) decoding for binary channels
.TP
.BR QccENTExponentialGolombEncodeSymbol (3)
exponential-Golomb encoding of single symbol
.TP
.BR QccENTExponentialGolombDecodeSymbol (3)
exponential-Golomb decoding of single symbol
.TP
.BR QccENTExponentialGolombEncode (3)
exponential-Golomb encoding
.TP
.BR QccENTExponentialGolombDecode (3)
exponential-Golomb decoding
.SS "UTILITY PROGRAMS"
.TP
.BR chnarithmeticencode (1)
adaptive arithmetic encoding of a channel
.TP
.BR chnarithmeticdecode (1)
adaptive arithmetic decoding of a channel
.TP
.BR chnhuffmanencode (1)
Huffman encoding of a channel
.TP
.BR chnhuffmandecode (1)
Huffman decoding of a channel
.TP
.BR chnagolombencode (1)
adaptive Golomb encoding of a channel
.TP
.BR chnagolombdecode (1)
adaptive Golomb deconding of a channel
.SH "SEE ALSO"
.BR QccPackSQ (3),
.BR QccPackVQ (3),
.BR QccPackAVQ (3),
.BR QccPackIMG (3),
.BR QccPackWAV (3),
.BR QccPack (3)
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
