.TH QCCMATRIXADDNOISETOREGION 3 "QCCPACK" ""
.SH NAME
QccMatrixAddNoiseToRegion
\- corrupt region of matrix with random noise
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccMatrixAddNoiseToRegion(QccMatrix " matrix ", int " num_rows ", int " num_cols ", int " start_row ", int " start_col ", int " region_num_rows ", int " region_num_cols ", double " noise_variance );
.SH DESCRIPTION
.B QccMatrixAddNoiseToRegion()
adds uniformly-distributed random noise of variance
.I noise_variance
to a rectangular region in
.IR matrix .
.I num_rows
and
.I num_cols
give the dimensions of
.IR matrix ,
.I start_row
and
.I start_row
give the coordinates (within 
.IR matrix )
of the upper-left corner of the region to be corrupted with noise,
and
.I region_num_rows
and
.I region_num_cols
give the size of the noise-corrupted region.
.B QccMatrixAddNoiseToRegion()
will properly handle cases in which the specified rectangular region extends
beyond the boundaries of
.IR matrix .
.LP
The random noise added to
.I matrix
is uniform, has zero mean,
and has variance
.IR noise_variance .
The noise is generated using
.BR QccMathRand (3).
.SH "SEE ALSO"
.BR QccMatrix (3),
.BR QccMathRand (3),
.BR QccPack (3)
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
