.TH QCCMATRIXNULLSPACE 3 "QCCPACK" ""
.SH NAME
QccMatrixNullspace
\- generate orthonormal basis for nullspace of matrix
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccMatrixNullspace(const QccMatrix " matrix1 ", int " num_rows ", i " num_cols ", QccMatrix " matrix2 ", int *" num_cols2 );
.SH DESCRIPTION
.B QccMatrixNullspace()
creates an orthonormal basis for the nullspace of
.IR matrix1
which is a matrix of size
.IR num_rows
x
.IR num_cols .
This orthonormal basis is returned as the columns of
.IR matrix2 ;
that is, the columns of
.IR matrix2
span the space that is orthogonal to the space spanned
by the columns of
.IR matrix1 .
.IR matrix2
must be allocated to be of size
.IR num_cols
x
.IR num_cols
prior to calling
.BR QccMatrixNullspace() 
(Note: this is
.B not
.IR num_rows
x
.IR num_cols !)
.LP
The number of basis vectors in the orthogonal nullspace basis is returned as
.IR num_cols2 ;
.IR num_cols2
will be less than
.IR num_cols .
.IR matrix2
will contain
.IR num_cols " - " num_cols2
columns of zeros.
If
.IR matrix1
is of full rank,
.IR num_cols2
will be zero, and
.IR matrix2
will be all zero.
.LP
.BR QccMatrixNullspace()
is implemented via a call to
.BR QccMatrixSVD (3)
to generate the singular value decomposition of
.IR matrix1 .
Then,
the right singular vectors corresponding to zero
singular values, if any, are returned in
.IR matrix2 .
.SH "SEE ALSO"
.BR QccMatrixSVD (3),
.BR QccMatrix (3),
.BR QccPack (3)
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
