.TH QCCMOVECOMPONENTTOFRONT 3 "QCCPACK" ""
.SH NAME
QccVectorMoveComponentToFront
\- move specified component to front of vector
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BR "int QccVectorMoveComponentToFront(QccVector " vector ", int " vector_dimension ", int " index );
.SH DESCRIPTION
.B QccVectorMoveComponentToFront()
permutes the components of
.IR vector .
The component at index
.IR index ,
.IR vector [ index ],
is moved to the front of
.I vector
(i.e., to the 
.IR vector [0]
position).
The components originally at indices 0 to
.IR index -1
are "shifted" one index higher to make room for the insertion
at the front of the vector.
The permuted vector is returned in
.IR vector .
.SH "SEE ALSO"
.BR QccPack (3)
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
