.TH KLTTCEENCODE3D 1 "QCCPACK" ""
.SH NAME
klttceencode3d, klttcedecode3d \-
encode/decode an image cube using the KLT+3D-TCE algorithm
.SH SYNOPSIS
.sp
.B klttceencode3d
.RB "[\|" \-w
.IR  wavelet "\|]"
.RB "[\|" \-b
.IR  boundary "\|]"
.RB "[\|" \-nl
.IR  num_levels "\|]"
.RB "[\|" \-a
.IR  alpha "\|]"
.RB "[\|" \-vo "\|]"
.I rate
.I icbfile
.I bitstream
.LP
.B klttcedecode3d
.RB "[\|" \-w
.IR  wavelet "\|]"
.RB "[\|" \-b
.IR  boundary "\|]"
.RB "[\|" \-r
.IR  rate "\|]"
.I bitstream
.I icbfile
.SH OPTIONS
.TP
.BI \-w " wavelet"
String. 
Name of the wavelet file
.RB ( FBK
or
.B LFT
format); default = "CohenDaubechiesFeauveau.9-7.lft"
.TP
.BI \-b " boundary"
String. Type of boundary extension; default = "symmetric".
.TP 
.BI \-nl " num_levels"
Integer. Number of levels of dyadic spatial decomposition;
default value is 5 levels.
.TP
.BI \-a " alpha"
Float. Value of the learning-rate parameter alpha; default is 0.2.
.TP
.BI \-r " rate"
Float. Rate at which to stop decoding. Default is to decode until
end of input bitstream is reached.
.TP
.B \-vo
Print only the value of the rate to stdout (terse output);
default is verbose output.
.SH DESCRIPTION
.LP
.B klttceencode3d
codes an image cube,
.IR icbfile ,
using the KLT+3D-TCE algorithm;
see
.BR QccWAVklttce3DEncode (3)
for more detail.
.LP
The transform is a hybrid combination of a spectral KLT
plus a dyadic DWT applied spatially.
The
.B \-w
option specifies the wavelet, the
.B \-b
option specifies the boundary extension, and
the
.BR \-nl ,
option specifies the number of decomposition levels for the
spatial DWT.
.LP
The KLT+3D-TCE algorithm performance is determined in part through
the parameter
.IR alpha ,
a value that gives the learning rate of the density-estimation
process implemented by the tarp filter used in one of
the coding passes of the TCE algorithm.
.LP
The desired bitrate of the output
.I bitstream
is specified by
.IR rate ,
which is expressed in bits per voxel of the original image.
.B klttceencode3d
normally prints to stdout a small amount of information
concerning this target bitrate and the actual bitrate achieved.
Usually these rates are identical, but may differ slightly.
If the 
.B \-vo
(value-only) option is given, all printed output is suppressed except for
the actual bitrate.
.LP
.B klttcedecode3d
performs the corresponding decoding using the KLT+3D-TCE algorithm, decoding
the
.I bitstream
made by
.B klttceencode3d
and producing
a reconstructed image cube,
.IR icbfile .
For sane results, 
.IR wavelet 
and
.IR boundary 
should be the same as they were for
.BR klttceencode3d .
If a decoding rate is specified with the
.B \-r
option, then
.B klttcedecode3d
stops decoding when
.I rate
bits per voxel from the input bitstream
have been decoded. Otherwise, decoding stops when the
end of the input bitstream is reached.
.LP
.BR klttceencode3d
and
.BR klttcedecode3d
call
.BR QccWAVklttce3DEncode (3)
and
.BR QccWAVklttce3DDecode (3),
respectively, to perform KLT+3D-TCE encoding and decoding.
Refer to the man pages for these functions for more information
on the details of the QccPack implementation of the KLT+3D-TCE algorithm.
.SH "SEE ALSO"
.BR QccWAVklttce3DEncode (3),
.BR QccWAVklttce3DDecode (3),
.BR QccWAVSubbandPyramid3D (3),
.BR QccPackWAV (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.LP
J. Zhang, J. E. Fowler, and G. Liu,
"Lossy-to-Lossless Compression of Hyperspectral Imagery Using
3D-TCE and an Integer KLT," 
.IR "IEEE Geoscience and Remote Sensing Letters" ,
vol. 5, pp. 814-818, October 2008.

C. Tian and S. S. Hemami, "An Embedded Image Coding System
Based on Tarp Filter with Classification," in
.IR "Proceedings of the International Conference on Acoustics, Speech, and Signal Processing" ,
Montreal, Quebec, Canada, May 2004, vol. 3, pp. 49-52.

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


