.TH SBPTOICP 1 "QCCPACK" ""
.SH NAME
sbptoicp \- convert subband pyramid to image component
.SH SYNOPSIS
.B sbptoicp
.I subband\_pyramid
.I icpfile
.SH DESCRIPTION
.LP
.B sbptoicp
reads the multi-level subband pyramid
.I subband\_pyramid
.RB ( SBP
format with
.I L
>= 1 in the header) and converts it into a 
.I single
.BR ICP -format
image file,
.IR icpfile .
.B sbptoicp
consists of simply copying the matrix of the subband pyramid
without regard to the individual subbands therein.
.SH "SEE ALSO"
.BR icptosbp (1),
.BR imgdwt (1),
.BR imgidwt (1),
.BR QccPackWAV (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
