#!/bin/sh

usage()
{
  echo "usage: `basename $0` logfile"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

DATE=`date`

echo >>$1
echo >>$1
echo ------------------------------------------------------------------------ >>$1
echo >>$1
echo >>$1
echo Process finished on $HOST --- $DATE >> $1
echo >>$1
echo >>$1
echo ------------------------------------------------------------------------ >>$1


