.TH ICPTODAT 1 "QCCPACK" ""
.SH NAME
icptodat \- converts image component to dataset
.SH SYNOPSIS
.B icptodat
.RB "[\|" \-ts
.IR  tilesize "\|]"
.RB "[\|" \-tw
.IR  tilewidth "\|]"
.RB "[\|" \-th
.IR tileheight "\|]"
.I icpfile
.I datfile
.SH OPTIONS
.TP
.BI \-ts " tilesize"
Integer. Size of square tiles
.TP
.BI \-tw " tilewidth"
Integer. Horizontal width of rectangular tiles
.TP
.BI \-th " tileheight"
Integer. Vertical height of rectangular tiles
.SH DESCRIPTION
.LP
.B icptodat
converts
.IR icpfile ,
a ICP-format image component, to
dataset
.IR datfile ,
a DAT-format file.
Two-dimensional tiles are extracted from 
.I icpfile
in raster-scan order, converted to one-dimensional
vectors, and written sequentially to
.IR datfile .
Option
.B \-ts 
specifies that square tiles of size
.RI sqrt( tilesize ") x sqrt(" tilesize ) 
are extracted from 
.I icpfile
and written to 
.I datfile 
as vectors with dimension 
.IR tilesize .
The 
.B \-tw 
and 
.B \-th 
options are used together to specify that
vectors of dimension 
.IR tilewidth " x " tileheight 
are written to
.I datfile 
from rectangular tiles extracted from 
.IR icpfile .
Note: either 
.B \-ts 
or 
.B \-tw 
and 
.B \-th 
must be given.
.LP
If the image component
.I icpfile
does not have size that is a multiple of the requested tile size,
then tiles are extracted from the upper-left part of the image.  Leftover
rows and/or columns at the bottom and right sides of the image, if any,
are ignored and not output to
.IR datfile .
.LP
.BR icptodat
calls
.BR QccIMGImageComponentToDataset (3).
.SH "SEE ALSO"
.BR dattoicp (1),
.BR QccIMGImageComponentToDataset (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
