.TH IMGTOICP 1 "QCCPACK" ""
.SH NAME
imgtoicp \- converts image to image component
.SH SYNOPSIS
.B imgtoicp
.I imgfile
.I icpfiles...
.SH DESCRIPTION
.LP
.B imgtoicp
converts and image
.IR imgfile ,
to ICP-format image components,
.IR icpfiles .
.LP
If
.I imgfile
is a color image,
.B imgtoicp
requires that three output
.I icpfiles
be specified, one for each of the Y, U, and V components of the image,
in order.
Otherwise, for grayscale images,
only one
.I icpfile
is to be specified.
.LP
Note: converting from PGM or PPM format to ICP format implies simply converting
integer pixels to floating-point values.
.SH "SEE ALSO"
.BR icptoimg (1)
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
