.TH SEQDEINTERLACE 1 "QCCPACK" ""
.SH NAME
seqdeinterlace \- deinterlace image sequence
.SH SYNOPSIS
.B seqdeinterlace
.RB "[\|" \-ss "\|]"
.I seqfile1
.I seqfile2
.SH OPTIONS
.TP
.B \-ss
Supersample -- interlace both top and bottom fields to separate frames.
.SH DESCRIPTION
.LP
.B seqdeinterlace
converts interlaced-scanned images of sequence
.I seqfile1
to progressive-scanned images which are output to
.IR seqfile2 
via
.BR QccIMGImageSequenceDeinterlace (3).
.SH "SEE ALSO"
.BR QccIMGImageSequenceDeinterlace (3),
.BR QccIMGImageSequence (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
