.TH QCCIMGIMAGECUBECLIP 3 "QCCPACK" ""
.SH NAME
QccIMGImageCubeClip,
QccIMGImageCubeNormalize \- 
clip and normalize image cube
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccIMGImageCubeClip(QccIMGImageCube *" image_cube );
.br
.BI "int QccIMGImageCubeNormalize(QccIMGImageCube *" image_cube );
.SH DESCRIPTION
This routine assumes that the range of permissible voxel values in
.I image_cube
is be 0 to 255, which is the common range for 8-bit images.
.LP
.BR QccIMGImageCubeClip()
calls
.BR QccIMGImageComponentClipPixel()
for each voxel in
.IR image_cube ,
effectively ensuring that each pixel in
.IR image_cube
is clipped to the 0-255 range.
.LP
.BR QccIMGImageCubeNormalize()
expands or contracts the dynamic range of the voxel values in
.IR image_cube
to the 0-255 range.
.BR QccIMGImageCubeNormalize()
maps the range
.IR image_cube->min_val
to
.IR image_cube->max_val
to the range 0-255 in a linear fashion.
.IR image_cube->min_val
and
.IR image_cube->max_val
must be set correctly via a call to
.BR QccIMGImageCubeSetMaxMin (3)
prior to calling
.BR QccIMGImageCubeNormalize() .
.SH "RETURN VALUES"
These routines return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccIMGImageComponentClipPixel (3)
.BR QccIMGImageCube (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



