.TH QCCIMGIMAGECOMPONENTSCALARQUANTIZE 3 "QCCPACK" ""
.SH NAME
QccIMGImageComponentScalarQuantize,
QccIMGImageComponentInverseScalarQuantize,
QccIMGImageScalarQuantize,
QccIMGImageInverseScalarQuantize,
\- 
scalar quantization of images and image components
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccIMGImageComponentScalarQuantize(const QccIMGImageComponent *" image_component ", const QccSQScalarQuantizer *" quantizer ", QccVector " distortion ", QccChannel *" channel );
.br
.BI "int QccIMGImageComponentInverseScalarQuantize(const QccChannel *" channel ", const QccSQScalarQuantizer *" quantizer ", QccIMGImageComponent *" image_component );
.br
.sp
.BI "int QccIMGImageScalarQuantize(const QccIMGImage *" image ", const QccSQScalarQuantizer *" quantizers ", QccChannel *" channels );
.br
.BI "int QccIMGImageInverseScalarQuantize(const QccChannel *" channels ", const QccSQScalarQuantizer *" quantizers ", QccIMGImage *" image );
.SH DESCRIPTION
.BR QccIMGImageComponentScalarQuantize()
calls
.BR QccSQScalarQuantization (3)
for each pixel in
.IR image_component ,
effectively scalar quantizing the pixel with
.IR quantizer .
The resulting quantization indices are returned in
.IR channel
which must be allocated prior to calling
.BR QccIMGImageComponentScalarQuantize() .
If
.IR distortion
is not
.BR NULL ,
the squared-error distortion between each pixel and its quantized
reconstruction is returned in
.IR distortion .
.LP
.BR QccIMGImageComponentInverseScalarQuantize()
inverse quantizes the quantization indices in
.IR channel ,
reconstructing the pixels which are returned in
.IR image_component .
.LP
.BR QccIMGImageScalarQuantize()
and
.BR QccIMGImageInverseScalarQuantize()
call
.BR QccIMGImageComponentScalarQuantize()
and
.BR QccIMGImageComponentInverseScalarQuantize() ,
respectively, for each of the
.IR Y ,
.IR U ,
and
.IR V
components of
.IR image .
.IR quantizers
and
.IR channels
are arrays of quantizers and channels,
one for each image component.
.SH "RETURN VALUE"
These routines return 0 on success, 1 on failure.
.SH "SEE ALSO"
.BR QccSQScalarQuantization (3),
.BR QccSQInverseScalarQuantization (3),
.BR QccIMGImageComponent (3),
.BR QccIMGImage (3),
.BR QccChannel (3),
.BR QccPackIMG (3),
.BR QccPack (3)

A. K. Jain,
.IR "Fundamentals of Digital Image Processing" .
Englewood Cliffs, NJ: Prentice Hall, 1989.

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
