.TH QCCIMGIMAGEEXTRACTFRAME 3 "QCCPACK" ""
.SH NAME
QccIMGImageExtractFrame
\- 
extract a single frame from image cube
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccIMGImageCubeExtractFrame(const QccIMGImageCube *" image_cube ", int " frame ", QccIMGImageComponent *" image_component );
.SH DESCRIPTION
.BR QccIMGImageExtractFrame()
extracts the single frame indicated by
.I frame
from
.IR image_cube
into
.IR image_component ,
a
.BR QccIMGImageComponent (3)
structure.
.IR image_component
must be allocated prior to calling
.BR QccIMGImageCubeExtractFrame()
and must have the same number of rows and columns as
.IR image_cube .
.SH "RETURN VALUES"
These routines return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccIMGImageCube (3),
.BR QccIMGImageComponent (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



