.TH QCCIMGIMAGECOMPONENTCOPY 3 "QCCPACK" ""
.SH NAME
QccIMGImageComponentCopy,
QccIMGImageComponentAdd,
QccIMGImageComponentSubtract
\- 
copy and arithmetic operations on image components
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccIMGImageComponentCopy(QccIMGImageComponent *" image_component1 ", const QccIMGImageComponent *" image_component2 );
.br
.BI "int QccIMGImageComponentAdd(const QccIMGImageComponent *" image_component1 ", const QccIMGImageComponent *" image_component2 ", QccIMGImageComponent *" image_component3 );
.br
.BI "int QccIMGImageComponentSubtract(const QccIMGImageComponent *" image_component1 ", const QccIMGImageComponent *" image_component2 ", QccIMGImageComponent *" image_component3 );
.SH DESCRIPTION
.BR QccIMGImageComponentCopy()
copies the contents of
.IR image_component2
into
.IR image_component1 .
If
.IR image_component1
has not yet been allocated, it is allocated to the same size as
.IR image_component2
with a call to
.BR QccIMGImageComponentAlloc (3).
If
.IR image_component1
is allocated, it must be the same size as
.IR image_component2 .
.LP
.BR QccIMGImageComponentAdd()
adds
.IR image_component1
to
.IR image_component2 ,
pixel by pixel,
returning the result in
.IR image_component3 .
.IR image_component3
must be allocated prior to calling
.BR QccIMGImageComponentAdd() ,
and
.IR image_component1 ,
.IR image_component2 ,
and
.IR image_component3
must all be the same size.
.LP
.BR QccIMGImageComponentSubtract()
subtracts
.IR image_component2
from
.IR image_component1 ,
pixel by pixel,
returning the result in
.IR image_component3 .
.IR image_component3
must be allocated prior to calling
.BR QccIMGImageComponentSubtract() ,
and
.IR image_component1 ,
.IR image_component2 ,
and
.IR image_component3
must all be the same size.
.SH "RETURN VALUES"
These routines return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccIMGImageComponent (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



