.TH QCCIMGIMAGECUBECOPY 3 "QCCPACK" ""
.SH NAME
QccIMGImageCubeCopy,
QccIMGImageCubeAdd,
QccIMGImageCubeSubtract
\- 
copy and arithmetic operations on image cubes
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccIMGImageCubeCopy(QccIMGImageCube *" image_cube1 ", const QccIMGImageCube *" image_cube2 );
.br
.BI "int QccIMGImageCubeAdd(const QccIMGImageCube *" image_cube1 ", const QccIMGImageCube *" image_cube2 ", QccIMGImageCube *" image_cube3 );
.br
.BI "int QccIMGImageCubeSubtract(const QccIMGImageCube *" image_cube1 ", const QccIMGImageCube *" image_cube2 ", QccIMGImageCube *" image_cube3 );
.SH DESCRIPTION
.BR QccIMGImageCubeCopy()
copies the contents of
.IR image_cube2
into
.IR image_cube1 .
If
.IR image_cube1
has not yet been allocated, it is allocated to the same size as
.IR image_cube2
with a call to
.BR QccIMGImageCubeAlloc (3).
If
.IR image_cube1
is allocated, it must be the same size as
.IR image_cube2 .
.LP
.BR QccIMGImageCubeAdd()
adds
.IR image_cube1
to
.IR image_cube2 ,
voxel by voxel,
returning the result in
.IR image_cube3 .
.IR image_cube3
must be allocated prior to calling
.BR QccIMGImageCubeAdd() ,
and
.IR image_cube1 ,
.IR image_cube2 ,
and
.IR image_cube3
must all be the same size.
.LP
.BR QccIMGImageCubeSubtract()
subtracts
.IR image_cube2
from
.IR image_cube1 ,
voxel by voxel,
returning the result in
.IR image_cube3 .
.IR image_cube3
must be allocated prior to calling
.BR QccIMGImageCubeSubtract() ,
and
.IR image_cube1 ,
.IR image_cube2 ,
and
.IR image_cube3
must all be the same size.
.SH "RETURN VALUES"
These routines return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccIMGImageCube (3),
.BR QccPackIMG (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



