.TH SQTOCBK 1 "QCCPACK" ""
.SH NAME
sqtocbk \- convert from scalar quantizer to VQ codebook format
.SH SYNOPSIS
.B sqtocbk
.I sqfile
.I cbkfile
.SH DESCRIPTION
.LP
.B sqtocbk
converts from the scalar-quantizer format (SQ) used by scalar-quantization
routines (see 
.BR QccPackSQ (3))
to the VQ-codebook format (CBK) used by vector-quantization
routines.
The resulting VQ codebook,
.IR cbkfile ,
contains one-dimensional codewords.
.SH "SEE ALSO"
.BR QccPackSQ (3),
.BR QccPackVQ (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
