.TH KLT_TRAIN 1 "QCCPACK" ""
.SH NAME
klt_train \- KLT training on image cube
.SH SYNOPSIS
.B klt_train
.I icbfile
.I kltfile
.SH DESCRIPTION
.LP
.B klt_train
determines the KLT transform (mean vector and transform matrix)
for the given
.BR ICB -format
file
.IR icbfile .
The resulting KLT is written to
.IR kltfile ,
a
.BR KLT -format
file.
This KLT provides a transform for spectral decorrelation of
the hyperspectral image in
.IR icbfile ;
the KLT training is accomplished via a call to
.BR QccHYPkltTrain (3).
.LP
See
.BR icbklt (1)
and
.BR icbiklt (1)
to apply
.IR klt
to the dataset as a forward transform or inverse transform, respectively.
.SH "SEE ALSO"
.BR QccHYPkltTrain (3),
.BR QccHYPklt (3),
.BR QccPackHYP (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
