.TH RAWTOICB 1 "QCCPACK" ""
.SH NAME
rawtoicb \- converts raw file to image cube
.SH SYNOPSIS
.B rawtoicb
.RB "[\|" \-s "\|]"
.RB "[\|" \-bpv
.IB bits_per_voxel "\|]"
.RB "[\|" \-bsq "\|]"
.RB "[\|" \-bil "\|]"
.RB "[\|" \-bip "\|]"
.RB "[\|" \-bend "\|]"
.RB "[\|" \-lend "\|]"
.I num_rows
.I num_cols
.I num_frames
.I rawfile
.I icbfile
.SH OPTIONS
.TP
.BI \-s
Indicates raw file contains signed values.
Default: raw file contains unsigned values.
.TP
.BI \-bpv
Indicates the number of bits per each voxel (sample) value.
Default is 16.
.TP
.BI \-bsq
Indicates raw file is stored in band-sequential (BSQ) order. This is
the default.
.TP
.BI \-bil
Indicates raw file is stored in band-interleaved-by-line (BIL) order.
.TP
.BI \-bip
Indicates raw file is stored in band-interleaved-by-pixel (BIP) order.
.TP
.BI \-bend
Indicates raw file contains 16-bit integers stored in
big-endian format. This is the default.
.TP
.BI \-lend
Indicates raw file contains 16-bit integers stored in
little-endian format.
.SH DESCRIPTION
.LP
.B rawtoicb
converts a raw file
containing a 3D array of integer samples (voxels) into a
.BR ICB -format
file. The size of the raw file must be given as
.IR num_rows ,
.IR num_cols ,
and
.IR num_frames
.RI ( num_frames
= number of spectral bands).
.LP
The option
.BR \-bpv
specifies the number of bits that each voxel value contains.
.IR bits_per_voxel
must be between 1 and 32. If
.IR bits_per_voxel
is <= 8, then each sample is stored in
.IR rawfile
as the least significant
bits in a single byte; otherwise, if
.IR bits_per_voxel
is <= 16, then each sample is stored in
.IR rawfile
as the least significant bits of two consecutive bytes (the default);
otherwise, if
.IR bits_per_voxel
is <= 32, then each sample is stored in
.IR rawfile
as the least significant bits of four consecutive bytes.
The option
.BR \-s
indicates that the raw file contains signed values;
unsigned is assumed if the
.BR \-s
option is absent.
The options
.BR \-bend
and
.BR \-lend
indicate whether the raw file is in
big-endian or little-endian
format, respectively.
If neither is specified,
big-endian is assumed.
.LP
The options
.BR \-bsq ,
.BR \-bil ,
and
.BR \-bip
indicate the scanning order of the rawfile;
see
.BR QccHYPRaw (3).
If none of
.BR \-bsq ,
.BR \-bil ,
or
.BR \-bip
are present,
BSQ is assumed.
.SH "SEE ALSO"
.BR icbtoraw (1),
.BR QccHYPRaw (3),
.BR QccPackHYP (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
