.TH GYDECODE 1 "QCCPACK" ""
.SH NAME
gydecode \- decoder for the Gersho-Yano AVQ algorithm
.SH SYNOPSIS
.B gydecode
.I channelfile
.I sideinfofile
.I codebook
.I codebook\_coder
.I datfile
.SH DESCRIPTION
.LP
.B gydecode
decodes a channel,
.I channelfile
(CHN format), and side information,
.I sideinfofile
(SID format), both produced by
.BR gyencode ,
and writes the resulting output data to
.IR datfile .
That is, 
.B gydecode
performs VQ-index lookup of the indices in
.I channelfile
while updating the VQ codebook as dictated by
.IR sideinfofile .
.B gydecode
starts decoding using the initial codebook specified
by
.I codebook
(which should be the same initial codebook originally used by
.BR gyencode ).
.I codebook\_coder
(SQ format) gives the scalar quantizer used to decode the side information.
.SH "SEE ALSO"
.BR gyencode (1),
.BR avqrate (1),
.BR QccPackAVQ (3),
.BR QccPack (3)

A. Gersho and M. Yano, "Adaptive Vector Quantization by Progressive
Codevector Replacement," Proc. ICASSP, pp. 133-136, 1985.

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
