.TH ARITHMETIC_SEQUENCE 1 "QCCPACK" ""
.SH NAME
arithmetic\_sequence \- output arithmetic sequence of numbers
.SH SYNOPSIS
.B arithmetic\_sequence
.I start
.I stop
.I num\_values
.SH DESCRIPTION
.LP
.B arithmetic\_sequence
prints an arithmetic sequence of floating-point values to stdout.
The sequence starts with value
.IR start ,
ends with value
.IR stop ,
and contains 
.I num\_values
values.
.SH "SEE ALSO"
.BR QccPack (3)


.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
