.TH QCCWAVSUBBANDPYRAMIDINTREAD 3 "QCCPACK" ""
.SH NAME
QccWAVSubbandPyramidIntRead, QccWAVSubbandPyramidIntWrite \- 
read/write integer-valued subband pyramid to/from file
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccWAVSubbandPyramidIntRead(QccWAVSubbandPyramidInt *" subband_pyramid );
.br
.BI "int QccWAVSubbandPyramidIntWrite(const QccWAVSubbandPyramidInt *" subband_pyramid );
.SH DESCRIPTION
.B QccWAVSubbandPyramidIntRead()
reads a 
.B QccWAVSubbandPyramidInt
structure from a file; the filename of the 
.BR SBPI -format
file to be read must be stored as
.IR subband_pyramid->filename .
.LP
.B QccWAVSubbandPyramidIntWrite()
writes a
.B QccWAVSubbandPyramidInt
structure to a file; the filename of the 
.BR SBPI -format
file to be written must be stored as
.IR subband_pyramid->filename .
.SH "RETURN VALUES"
Both
.BR QccWAVSubbandPyramidIntRead()
and
.BR QccWAVSubbandPyramidIntWrite()
return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccWAVSubbandPyramidInt (3),
.BR QccPackWAV (3),
.BR QccPack (3)
.LP
A. R. Calderbank, I. Daubechies, W. Sweldens, B.-L. Yeo, "Lossless
Image Compression Using Integer to Integer Wavelet Transforms", in
.IR "Proceedings of the International Conference on Image Processing" ,
Lausanne, Switzerland, pp. 596-599, September 1997.

Z. Xiong, X. Wu, S. Cheng, J. Hua, "Lossy-to-Lossless Compression of
Medical Volumetric Data Using Three-Dimensional Integer Wavelet Transforms,"
.IR "IEEE Transactions on Medical Imaging" ,
vol. 22, pp. 459-470, March 2003.

M. Antonini, M. Barlaud, P. Mathieu, and I. Daubechies,
"Image Coding Using Wavelet Transform,"
.IR "IEEE Transactions on Image Processing" ,
vol. 1, pp. 205-220, April 1992.
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



