.TH QCCWAVSUBBANDPYRAMIDRASTERSCAN 3 "QCCPACK" ""
.SH NAME
QccWAVSubbandPyramidRasterScan, QccWAVSubbandPyramidInverseRasterScan \- 
raster scanning of subband-pyramid subbands
.SH SYNOPSIS
.B #include "libQccPack.h"
.sp
.BI "int QccWAVSubbandPyramidRasterScan(const QccWAVSubbandPyramid *" subband_pyramid ", QccVector " scanned_coefficients );
.br
.BI "int QccWAVSubbandPyramidInverseRasterScan(QccWAVSubbandPyramid *" subband_pyramid ", const QccVector " scanned_coefficients );
.SH DESCRIPTION
.BR QccWAVSubbandPyramidRasterScan()
performs a raster scan on each subband in
.IR subband_pyramid ,
returning the scanned coefficients in
.IR scanned_coefficients .
Each subband is scanned from upper left to lower right, and the subbands
are scanned starting with the baseband and going to the highest-frequency
subbands.
.LP
.BR QccWAVSubbandPyramidInverseRasterScan()
reverses the raster-scan process, filling
.I subband_pyramid
with the cofficients from
.IR scanned_coefficients .
.LP
For both of these routines,
.I subband_pyramid
and
.I scanned_coefficients
must be allocated before the routines are called.
.SH "RETURN VALUES"
These routines
return 0 on success and 1 on error.
.SH "SEE ALSO"
.BR QccWAVSubbandPyramid (3),
.BR QccWAVWavelet (3),
.BR QccPackWAV (3),
.BR QccPack (3)
.LP
.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them an.or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



