.TH SQENCODE 1 "QCCPACK" ""
.SH NAME
sqencode \- encoding using scalar quantization
.SH SYNOPSIS
.B sqencode
.I datfile
.I quantizer
.I channel
.SH DESCRIPTION
.LP
.B sqencode
encodes
.I datfile
(DAT format) using scalar quantization (SQ).
.B sqencode
uses input
.I quantizer
(SQ format)
as the SQ codebook and
outputs a channel of SQ indices to
.I channel 
(CHN format).
In general, 
.I datfile
consists of vectors, and 
the scalar quantizer is applied separately to each vector component.
.SH "SEE ALSO"
.BR sqdecode (1),
.BR squniform (1),
.BR sqlloyd (1),
.BR QccPackSQ (3),
.BR QccPack (3)

.SH AUTHOR
Copyright (C) 1997-2016  James E. Fowler
.\"  The programs herein are free software; you can redistribute them and/or
.\"  modify them under the terms of the GNU General Public License
.\"  as published by the Free Software Foundation; either version 2
.\"  of the License, or (at your option) any later version.
.\"  
.\"  These programs are distributed in the hope that they will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with these programs; if not, write to the Free Software
.\"  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
